---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: terraform-git-cli
  labels:
    app.kubernetes.io/version: "0.2"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: CLI
    tekton.dev/tags: cli
    tekton.dev/displayName: "terraform cli"
    tekton.dev/platforms: "linux/amd64"
spec:
  description: >-
    Terraform is an open-source infrastructure as code software tool created by HashiCorp.

    It enables users to define and provision a datacenter infrastructure using a high-level
    configuration language known as Hashicorp Configuration Language (HCL), or optionally JSON

    This Task will do a terraform init before it executes the actual configured ARGS from parameter.
  workspaces:
  - name: source
  params:
  - name: buildRevision
  - name: terraformGitURL
    description: The GitHub Repository for Terraform
  - name: terraformFolder
    description: The folder to execute Terraform Template
  - name: ARGS
    description: The terraform cli commands to tun
    type: array
    default:
    - "--help"
  - name: terraform-secret
    description: The terraform secret with credentials
    type: string
    default: "terraform-creds"
  - name: image
    description: the terraform image to use
    type: string
    default: docker.io/hashicorp/terraform:light
  - name: httpProxy
    description: HTTP proxy server for non-SSL requests
    type: string
    default: ""
  - name: httpsProxy
    description: HTTPS proxy server for SSL requests
    type: string
    default: ""
  - name: noProxy
    description: no proxy - opt out of proxying HTTP/HTTPS requests
    type: string
    default: ""
  steps:
    - name: git-checkout
      image: $(params.image)
      workingDir: $(workspaces.source.path)/$(params.terraformFolder)
      script: |
        #!/usr/bin/env sh
        set -e

        eval $(ssh-agent)
        ssh-add ~/.ssh/id_*
        git config --global core.sshCommand 'ssh -o StrictHostKeyChecking=accept-new'

        git init
        git remote add origin $(params.terraformGitURL)
        git fetch --depth 1 origin $(params.buildRevision)
        git checkout FETCH_HEAD
        pwd
        ls
    - name: init
      image: $(params.image)
      workingDir: /workspace/source/$(params.terraformFolder)
      command: ["terraform"]
      env:
        - name: "HTTP_PROXY"
          value: $(params.httpProxy)
        - name: "HTTPS_PROXY"
          value: $(params.httpsProxy)
        - name: "HTTP_PROXY"
          value: $(params.httpProxy)
      args:
        - "init"
    - name: terraform-cli
      image: $(params.image)
      workingDir: /workspace/source
      command: ["terraform"]
      args:
        - "$(params.ARGS)"
      env:
        - name: "HTTP_PROXY"
          value: $(params.httpProxy)
        - name: "HTTPS_PROXY"
          value: $(params.httpsProxy)
        - name: "HTTP_PROXY"
          value: $(params.httpProxy)
      envFrom:
        - secretRef:
            name: $(params.terraform-secret)